image: node:11.14.0-stretch

test:
  except:
    - master
    - release
    - tags
  script:
    - npm install
    - npm test

release:
  only:
    - release@getto-systems-labo/codes/docs
  script:
    - ./bin/push_tags.sh
